WELCOME = [ 
    """
    WELCOME TO THIS GAME OF HANGMAN, TRY YOUR LUCK AT GUESSING THE WORD!\n
    BUT BEWARE, ONCE YOUR LIVES ARE UP, YOUR LUCK HAS RUN OUT\n
    YOU'LL MEET THE SAME FAITH AS THOSE BEFORE YOU AND THOSE WHO DARE AFTER\n
    GOOD LUCK!
    """
]